language: node_js
branches:
  only:
    - master
    - firebase
    - http2
    - /^greenkeeper/.*$/
cache:
  yarn: true
  directories:
    - node_modules
notifications:
  email: false
node_js:
  - node
script:
  - npm run build:ssr
